### ISSUE TITLE
Resolving dependencies Issue with Deta 0.8 

### ISSUE THREAD

**Issue by scuervo91** [rickh94/ODetaM#1]
Hi, I'd like to use `odetam`, however the version of deta specified in the pyproyect.toml file is ^0.7.0. Which in my case the poetry version solving failed because I have the 0.8 version.  

I'd like to ask you if there's any chance to update the dependency deta to `^0.7` instead of `^0.7.0`. to be able to run with Deta 0.8.

**Comment by rickh94** [comment]
Hi, thanks for your interest and I'm sorry I didn't see this sooner. I think that I've fixed it with version 1.0.4, which is up on pypi now.
