### ISSUE TITLE
Undefined fields passed as None

### ISSUE THREAD

**Issue by ohtie** [rickh94/ODetaM#10]
If field is not specified in database _deserialize method define it as None. But that solution produce confusing moment when you declare new field in model with default value but it still takes None and raise exception. I think better ignore not specified fields, so them could be set as default or processed in validators. I maybe will do it myself later and suggest PR

**Comment by rickh94** [comment]
I think I understand what you are saying. I can slightly change the deserialize implementation to handle explicit `None`s and missing keys separated and let pydantic set the fields to default values or `None`. If the field doesn't have a default value, it will be set to `None` anyway by pydantic. If the field is require and does not have a default value, pydantic will error.

**Comment by rickh94** [comment]
Take a look at #11 and see if that behavior makes sense to you

**Comment by mamsdeveloper** [comment]
I mean such situation, when I don't have "order_manage_mode" field in Data Base and need set default. 
Yep, #11 fix it, thanks

![Screenshot 2023-04-14 044719](https://user-images.githubusercontent.com/69919896/231920614-d3402252-96e9-41dc-bdfc-ce18b9124cf6.png)

**Comment by ohtie** [comment]
#11 produce new bag. Now extra fields in constructor skipped and warning not shown.

**Comment by rickh94** [comment]
Can you provide a code example? I'm not sure what you mean by extra fields. Most of the constructor behavior is handled by [pydantic](https://pydantic.dev/). I didn't touch the constructor or serializer in the patch, so no behavior has changed there, only in the deserializer.

**Comment by ohtie** [comment]
Ok, I check and found out that it is correct pydantic behavior
